services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./Front
    ports:
      - "8080:8080"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
